added batch writes in Activity and Option ViewModels
Fun-Gen/Fun-Gen pull request #36
Opened 2022-05-21 02:36 UTC by j-cse

2022-05-21 03:27 UTC, j-cse commented
Whoops ran unit tests on another branch before pushing. Will fix batch writes

2022-05-21 05:13 UTC, j-cse commented
Not sure how to handle compiler warning for this on line 65

> Consider using asynchronous alternative function

```swift
batch.commit { error in
            if let error = error {
                print("Error writing batch \(error)")
            } else {
                print("Batch write succeeded.")
            }
        }
```

2022-05-23 19:26 UTC, ApolloZhu commented
You should be able to write

```swift
//   V wait for commit to finish before return
try await batch.commit()
//^ allow proper error reporting
```

2022-05-23 19:28 UTC, ApolloZhu requested changes

2022-05-23 19:28 UTC, ApolloZhu commented on Shared/ViewModel/ActivityViewModel.swift
>          }
It's really this part that needs to be included in the batch commit

2022-05-23 19:28 UTC, ApolloZhu commented on Shared/ViewModel/OptionViewModel.swift
> +        }
Should use try await

2022-05-24 22:15 UTC, merged