Ae/friendtagging
Fun-Gen/Fun-Gen pull request #44
Opened 2022-05-25 21:06 UTC by anrattanasouk

We created an array called friendID that gets appended a new user id every time a new username gets inputted, but no id seems to show up.

2022-05-25 22:41 UTC, ApolloZhu requested changes

2022-05-25 22:41 UTC, ApolloZhu commented on Shared/View/CreateActivityView.swift
> +// function? returns a list
Elaborate?

2022-05-25 22:41 UTC, ApolloZhu commented on Shared/View/CreateActivityView.swift
> +                            print(error)
Add // TODO: handle error whenever you just print it out

2022-05-25 22:41 UTC, ApolloZhu commented on Shared/View/CreateActivityView.swift
> +                            try await self.friendID.append(UserViewModel.user(named: self.newFriend)?.id ?? "no id")
It might be a better idea to not allow adding to friendList if no ID is found

2022-05-25 22:41 UTC, ApolloZhu commented on Shared/View/CreateActivityView.swift
>                      self.newFriend = ""
Note that Task is executed later asynchronously, so by then newFriend is already empty string. You'll want to cache the newFriend to a local variable for task to use.

2022-05-25 22:41 UTC, ApolloZhu commented on Shared/View/CreateActivityView.swift
> +    @State var newFriend: String = ""
Let's minimize the diff and put this back to between friendList and friendID

2022-05-26 01:31 UTC, ApolloZhu requested changes

2022-05-26 01:31 UTC, ApolloZhu commented on Shared/View/CreateActivityView.swift
> +                        showingAlert = true
Note that these variables are not used by anything. You'll need to actually add a `.alert` like in the other views

2022-05-26 01:31 UTC, ApolloZhu commented on Shared/View/CreateActivityView.swift
>                      self.friendList.append(self.newFriend)
Still adding to the friend list even if no ID is found

2022-05-26 01:31 UTC, ApolloZhu commented on Shared/View/CreateActivityView.swift
> +                            newFriendID = try await UserViewModel.user(named: self.newFriend)?.id ?? ""
1. I don't believe this fixes the issue, but please let me know if it does
2. Do we need to store newFriendID as a state?

2022-05-26 01:31 UTC, ApolloZhu commented on Shared/View/CreateActivityView.swift
> +                            if !newFriendID.isEmpty {
Should check for nil directly instead of defaulting to empty string then check for empty.

2022-05-26 02:50 UTC, anrattanasouk commented on Shared/View/CreateActivityView.swift
> +// function? returns a list
scratch note

2022-05-26 20:35 UTC, ApolloZhu approved these changes

2022-05-26 20:35 UTC, merged